Repository fullstacktf/myment-front, pull requests merged in 2019-08, with the labels that each got.

#34 Main page and components
  src/App.vue
  src/components/AnimLogo.vue
  src/components/Button.vue
  src/components/Footer.vue
  src/components/Image.vue
  src/components/LandingPage.vue
  src/components/LoggedHeader.vue
  src/components/Login.vue
  src/components/LoginMenu.vue
  src/components/Main.1.vue
  src/components/Main2.vue
  src/components/NewsBar.vue
  src/components/Signin.vue
  src/components/SingleMenuLink.vue
  src/components/ToShort.vue
  src/components/__test__/Main.test.js
Labels: Priority: Critical

#36 Mock backend GeoJSON
  .babelrc
  jest.config.js
  package-lock.json
  package.json
  src/App.vue
  src/components/GenButton.vue
  src/components/IdeaItem.vue
  src/components/LoginMenu.vue
  src/components/Main.1.vue
  src/components/Main2.vue
  src/components/SiteInput.vue
  src/components/TimeLine.vue
  src/components/__test__/Main.test.js
  src/index.js
  src/router.js
  src/store.js
  src/store/actions.js
  src/store/mutations.js
  src/store/states.js
  src/views/Home_page/HomePage.vue
  src/views/Idea_adder/IdeaAdder.vue
  src/views/Landing_page/LandingPage.vue
  src/views/Short_generator/ShortGenerator.vue
  src/views/Short_generator/__test__/ShortGenerator.test.js
  src/views/Short_generator/__test__/__snapshots__/ShortGenerator.test.js.snap
  src/views/Short_generator/__test__/mockData.ts
  src/views/Short_generator/__test__/mockTypes.ts
  src/views/Tag_adder/TagAdder.vue
  src/views/User_profile/UserProfile.vue
Labels: Priority: Critical, feature, needs-review

#41 Testing
  .eslintrc.json
  .travis.yml
  _templates/generator/help/index.ejs.t
  _templates/generator/new/hello.ejs.t
  _templates/generator/with-prompt/hello.ejs.t
  _templates/generator/with-prompt/prompt.ejs.t
  _templates/tester/help/index.ejs.t
  _templates/tester/new/test.ejs.t
  package-lock.json
  src/components/LoggedHeader.vue
  src/components/Main.vue
  src/components/__test__/AnimLogo.test.js
  src/components/__test__/Button.test.js
  src/components/__test__/FakeLeaderboard.test.js
  src/components/__test__/Footer.test.js
  src/components/__test__/IdeaItem.test.js
  src/components/__test__/LoggedHeader.test.js
  src/components/__test__/Map.test.js
  src/components/__test__/NewsBar.test.js
  src/components/__test__/QuickActionsMenu.test.js
  src/components/__test__/SignUp.test.js
  src/components/__test__/SignUpMenu.test.js
  src/components/__test__/Signin.test.js
  src/components/__test__/__snapshots__/AnimLogo.test.js.snap
  src/components/__test__/__snapshots__/Button.test.js.snap
  src/components/__test__/__snapshots__/FakeLeaderboard.test.js.snap
  src/components/__test__/__snapshots__/Footer.test.js.snap
  src/components/__test__/__snapshots__/IdeaItem.test.js.snap
  src/components/__test__/__snapshots__/LoggedHeader.test.js.snap
  src/components/__test__/__snapshots__/Map.test.js.snap
  src/components/__test__/__snapshots__/NewsBar.test.js.snap
  src/components/__test__/__snapshots__/QuickActionsMenu.test.js.snap
  src/components/__test__/__snapshots__/SignUp.test.js.snap
  src/components/__test__/__snapshots__/SignUpMenu.test.js.snap
  src/components/__test__/__snapshots__/Signin.test.js.snap
  src/index.js
  src/test/mockBack.ts
  src/test/mockData.ts
  src/test/mockTypes.ts
  src/test/vueSetup.js
  src/views/Idea_adder/IdeaAdder.vue
  src/views/Idea_adder/__test__/IdeaAdder.test.js
  src/views/Idea_adder/__test__/__snapshots__/IdeaAdder.test.js.snap
  src/views/Landing_page/__test__/LandingPage.test.js
  src/views/Landing_page/__test__/__snapshots__/LandingPage.test.js.snap
  src/views/Short_generator/ShortGenerator.vue
  src/views/Short_generator/__test__/ShortGenerator.test.js
  src/views/Short_generator/__test__/__snapshots__/ShortGenerator.test.js.snap
  src/views/Tag_adder/__test__/TagAdder.test.js
  src/views/Tag_adder/__test__/__snapshots__/TagAdder.test.js.snap
  src/views/User_profile/UserProfile.vue
  src/views/User_profile/__test__/UserProfile.test.js
  src/views/User_profile/__test__/__snapshots__/UserProfile.test.js.snap
Labels: Priority: Medium, enhancement

#45 Home view fixed
  .prettierrc
  _templates/tester/new/test.ejs.t
  package-lock.json
  package.json
  public/assets/myment-logo.png
  public/index.html
  src/components/MapComponent.vue
  src/components/NewsBar.vue
  src/components/SignUpMenu.vue
  src/components/__test__/__snapshots__/NewsBar.test.js.snap
  src/components/__test__/__snapshots__/SignUpMenu.test.js.snap
  src/index.js
  src/router.js
  src/views/Home_view/Home.vue
  src/views/Home_view/__test__/Home.test.js
  src/views/Home_view/__test__/__snapshots__/Home.test.js.snap
  src/views/Landing_page/LandingPage.vue
  src/views/Landing_page/__test__/__snapshots__/LandingPage.test.js.snap
  src/views/Short_generator/ShortGenerator.vue
  src/views/Tag_adder/TagAdder.vue
Labels: Priority: High
